version: '3.4'

services:
  cryptochain:
    image: cryptochain
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
